version: '3.9'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kibana
    volumes:
      - ./files/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    depends_on:
      - es-coo02
  es-set-defaults:
    image: alpine:3.13.1
    container_name: es-set-defaults
    build:
      context: ./es-set-defaults
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-master01: # Master
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-master01
    environment:
      - node.name=es-master01
      - node.roles=master
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  es-master02: # Master
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-master02
    environment:
      - node.name=es-master02
      - node.roles=master
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  es-master03: # Master
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-master03
    environment:
      - node.name=es-master03
      - node.roles=master
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  es-data01: # Data
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-data01
    environment:
      - node.name=es-data01
      - node.roles=data
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-data02: # Data
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-data02
    environment:
      - node.name=es-data02
      - node.roles=data
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-data03: # Data
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-data03
    environment:
      - node.name=es-data03
      - node.roles=data
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
#  es-data04: # Data Content
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
#    container_name: es-data04
#    environment:
#      - node.name=es-data04
#      - node.roles=data_content
#      - cluster.name=cluster
#      - discovery.seed_hosts=es-master01,es-master02,es-master03
#      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
#      - bootstrap.memory_lock=true
#      - xpack.ml.enabled=true
#      - xpack.monitoring.collection.enabled=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - TAKE_FILE_OWNERSHIP=true
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    depends_on:
#      - es-master01
#      - es-master02
#      - es-master03
  es-data05: # Data Hot
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-data05
    environment:
      - node.name=es-data05
      - node.roles=data_hot
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-data06: # Data Warm
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-data06
    environment:
      - node.name=es-data06
      - node.roles=data_warm
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-data07: # Data Cold
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-data07
    environment:
      - node.name=es-data07
      - node.roles=data_cold
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-data08: # Data Hot
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-data08
    environment:
      - node.name=es-data08
      - node.roles=data_hot
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-data09: # Data Warm
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-data09
    environment:
      - node.name=es-data09
      - node.roles=data_warm
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-data10: # Data Cold
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-data10
    environment:
      - node.name=es-data10
      - node.roles=data_cold
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-coo01: # Coordinating Only for Indexer
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-coo01
    environment:
      - node.name=es-coo01
      - node.roles=
      - node.master=false
      - node.voting_only=false
      - node.data=false
      - node.ingest=false
      - node.ml=false
      - node.transform=false
      - node.remote_cluster_client=false
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-coo02: # Coordinating Only for Kibana
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-coo02
    environment:
      - node.name=es-coo02
      - node.roles=
      - node.master=false
      - node.voting_only=false
      - node.data=false
      - node.ingest=false
      - node.ml=false
      - node.transform=false
      - node.remote_cluster_client=false
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-transform01: # Transform & Remote Cluster Client
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-transform01
    environment:
      - node.name=es-transform01
      - node.roles=transform,remote_cluster_client
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-ml01: # Machine Learning & Remote Cluster Client
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-ml01
    environment:
      - node.name=es-ml01
      - node.roles=ml,remote_cluster_client
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-voting01: # Voting Only
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-voting01
    environment:
      - node.name=es-voting01
      - node.roles=master,voting_only
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-ingest01: # Ingest
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-ingest01
    environment:
      - node.name=es-ingest01
      - node.roles=ingest
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  es-remote01: # Remote Cluster Client
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: es-remote01
    environment:
      - node.name=es-remote01
      - node.roles=remote_cluster_client
      - cluster.name=cluster
      - discovery.seed_hosts=es-master01,es-master02,es-master03
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master01
      - es-master02
      - es-master03
  httpd01:
    image: httpd:2.4.43
    container_name: httpd01
    volumes:
      - httpd01-volume:/var/log/apache2
      - ./files/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
  ab01:
    image: docker.elastic.co/beats/auditbeat:7.11.0
    container_name: ab01
    volumes:
      - ./files/auditbeat/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml:ro
    command: [ "--strict.perms=false" ]
    depends_on:
      - ls-shipper01
  mb01:
    image: docker.elastic.co/beats/metricbeat:7.11.0
    container_name: mb01
    volumes:
      - ./files/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
    command: [ "--strict.perms=false" ]
    depends_on:
      - ls-shipper01
  pb01:
    image: docker.elastic.co/beats/packetbeat:7.11.0
    container_name: pb01
    volumes:
      - ./files/packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml:ro
    command: [ "--strict.perms=false" ]
    cap_add:
      - NET_ADMIN
    depends_on:
      - ls-shipper01
  fb01:
    image: docker.elastic.co/beats/filebeat:7.11.0
    container_name: fb01
    volumes:
      - ./files/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - httpd01-volume:/var/log/apache2:ro
    command: [ "--strict.perms=false" ]
    depends_on:
      - httpd01
      - ls-shipper01
  hb01:
    image: docker.elastic.co/beats/heartbeat:7.11.0
    container_name: hb01
    command: [ "--strict.perms=false" ]
    volumes:
      - ./files/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    depends_on:
      - ls-shipper01
  apm01:
    image: docker.elastic.co/apm/apm-server:7.11.0
    container_name: apm01
    volumes:
      - ./files/apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
  fastapi01:
    container_name: fastapi01
    build:
      context: ./fastapi01
  fastapi02:
    container_name: fastapi02
    build:
      context: ./fastapi02
  ls-shipper01:
    image: docker.elastic.co/logstash/logstash:7.11.0
    container_name: ls-shipper01
    volumes:
      - ./files/logstash-shipper/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./files/logstash-shipper/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - kafka1
      - kafka2
      - kafka3
  ls-indexer01:
    image: docker.elastic.co/logstash/logstash:7.11.0
    container_name: ls-indexer01
    volumes:
      - ./files/logstash-indexer/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./files/logstash-indexer/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - es-coo01
      - es-set-defaults
  kowl:
    container_name: kowl
    hostname: kowl
    build:
      context: ./kowl
      args:
        GO_VERSION: "1.17"
        NODE_VERSION: "14.17.6"
        KOWL_VERSION: "1.4.0"
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
  zookeeper1:
    container_name: zookeeper1
    hostname: zookeeper1
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    environment:
      ZOOKEEPER_ID: "1"
    volumes:
      - zookeeper1-data:/opt/app/data
      - zookeeper1-logs:/opt/app/logs
  zookeeper2:
    container_name: zookeeper2
    hostname: zookeeper2
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    environment:
      ZOOKEEPER_ID: "2"
    volumes:
      - zookeeper2-data:/opt/app/data
      - zookeeper2-logs:/opt/app/logs
  zookeeper3:
    container_name: zookeeper3
    hostname: zookeeper3
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    environment:
      ZOOKEEPER_ID: "3"
    volumes:
      - zookeeper3-data:/opt/app/data
      - zookeeper3-logs:/opt/app/logs
  kafka1:
    container_name: kafka1
    hostname: kafka1
    build:
      context: ./kafka
      args:
        KAFKA_VERSION: "2.8.0"
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      BROKER_ID: "1"
    volumes:
      - kafka1-data:/opt/app/data
      - kafka1-logs:/opt/app/logs
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
  kafka2:
    container_name: kafka2
    hostname: kafka2
    build:
      context: ./kafka
      args:
        KAFKA_VERSION: "2.8.0"
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      BROKER_ID: "2"
    volumes:
      - kafka2-data:/opt/app/data
      - kafka2-logs:/opt/app/logs
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
  kafka3:
    container_name: kafka3
    hostname: kafka3
    build:
      context: ./kafka
      args:
        KAFKA_VERSION: "2.8.0"
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      BROKER_ID: "3"
    volumes:
      - kafka3-data:/opt/app/data
      - kafka3-logs:/opt/app/logs
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

volumes:
  httpd01-volume:
  zookeeper1-data:
  zookeeper2-data:
  zookeeper3-data:
  zookeeper1-logs:
  zookeeper2-logs:
  zookeeper3-logs:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  kafka1-logs:
  kafka2-logs:
  kafka3-logs: